baseURL = "https://proffer.dev/"
languageCode = "en-us"
title = "Jacob Proffer"
theme = "proffer"

[params]
  description = "Senior Front-End Developer at Elegant Seagulls."
  images = ["/images/social.jpg"]
