name = "Jacob Proffer"
description = ""
homepage = ""
tags = ["military", "dark"]
features = ["sass", "js", "minification"]
min_version = "0.94.0"

[author]
  name = "Jacob Proffer"
  homepage = "https://proffer.dev/"
